### save
POST localhost:8080/students
Content-Type: application/json

{
  "name": "lee",
  "grade": 1
}

### save error
POST localhost:8080/students
Content-Type: application/json

{
  "name": "lee",
  "grade": 6
}

### findAll
GET localhost:8080/students
Content-Type: application/json

### findAllByGrade
GET localhost:8080/students/1
Content-Type: application/json
